### PR TITLE
Add a tutorial to push the build result to GitHub Pages

### LINKED ISSUE #14: [Docs] Add a tutorial to push the build result to GitHub Pages
To ease sharing the tweets archive by users without much technical knowledge, having a clear tutorial about how to do it with GitHub Pages would be nice.

It would also help when the archive files (`tweets.js`, `tweet.db`) weight more than 50MB and can't be added to a GitHub repository:
- #4

### PR DESCRIPTION
**Pull request by steren**
fix #14

### CODE REVIEW

**Review by nhoizey — APPROVED** [review]
Great doc, thanks!

**Comment by tbroyer** [comment]
Not at all how I'd do it these days: GitHub Pages now provide GitHub Actions so you can have your eleventy site built and deployed in a GitHub Action: https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow (which also means that you could setup a scheduled build and GitHub Secret to retrieve new tweets from Twitter and publish the new site automatically; just make sure you also correctly configure the `@actions/cache` action)

**Comment by steren** [comment]
PR welcome @tbroyer

**Comment by tbroyer** [comment]
I'll try it on my repo and contribute back when I confirmed it works :+1:

**Comment by nhoizey** [comment]
It currently can't work for large collections of tweets:
- #4

**Comment by tbroyer** [comment]
Well, it can: limit is now 100MB for "regular" files and you can use LFS for larger files.
(mine is "only" 30MB)
The documentation could also list both approaches.

**Comment by tbroyer** [comment]
Here's my take on it: https://github.com/tbroyer/tweetback/blob/main/.github/workflows/deploy.yml, deployed at https://tbroyer.github.io/tweetback/
I probably overthought the caching a bit, and I prepared but didn't setup automatic fetching of new tweets from the Twitter API.
Also note that I committed my package-lock.json so this is using `npm ci` for more reproducible builds (see also https://github.com/tweetback/tweetback/discussions/16)

WDYT?

**Comment by nhoizey** [comment]
@tbroyer could you please open an issue or a PR for a new doc file named `docs/deploy-to-github-pages-with-github-actions.md` or similar?

I think both ways to publish to GitHub Pages can be interesting, just like we have [many options to deploy Eleventy sites](https://www.11ty.dev/docs/deployment/#providers).

**Comment by PatrickJnr** [comment]
Is there a way to update the page updating from the API? so we don't have to push every so often with new data.

**Pull request merged**
