### PR TITLE
Filter out Circle Tweets

### PR DESCRIPTION
**Pull request by xdesro**
Hi hi! 

If you hate this implementation, let me know, there are certainly improvements that could be made but I figured scrappy was okay cause the repo is young :) thanks for your review.

One thing you might not be super stoked on is that this commit requires Circles data to be included, and doesn't fail gracefully if it isn’t. I can rework with that in mind if you'd like! Also, I kinda just threw this filtration into the import process where it seemed logical to me; open to better ideas for location.

### CODE REVIEW

**Comment by xdesro** [comment]
My feeling is that they were private-ish when I Tweeted them, I don’t think there’s any reason for them to be less private in a post-Twitter era!

**Comment by zachleat** [comment]
Oh! I’ve misunderstood, this removes them! Yeah definitely on board

**Comment by matthiasott** [comment]
Agree with everything you wrote (also the edits), @xdesro! If people use it for backup reasons, they should be able to include Circle tweets as well. But if people want to publish their archive, they should be able to opt out. 👏

**Comment by daviddarnes** [comment]
@xdesro I would change the amended setup steps to be a note at the end, something like:
> If you use [Twitter Circle](https://help.twitter.com/en/using-twitter/twitter-circle) and wish to hide those tweets from your archive repeat the steps shown for the `tweets.js` file with the `./data/twitter-circle-tweet.js` file as well.

…and then adjust the code to gracefully skip the step if the file / data is not there 👍🏻

**Pull request closed without merging**
